In [1]:
import scipy.io
import pandas as pd

In [2]:
# Load the .mat file
mat = scipy.io.loadmat('smarthand_dataset.mat')

# Display the keys
print(mat.keys())

dict_keys(['__header__', '__version__', '__globals__', 'tactile_data', 'IMU_data', 'object_id', 'valid_flag', 'session_id', 'objects', 'threshold'])


In [3]:
print("Header:", mat['__header__'])
print("Version:", mat['__version__'])
print("Globals:", mat['__globals__'])

Header: b'MATLAB 5.0 MAT-file Platform: posix, Created on: Mon Aug 10 08:59:15 2020'
Version: 1.0
Globals: []


In [4]:
# tactile_data:
print(type(mat['tactile_data']))
print(mat['tactile_data'].shape)

# Convert to DataFrame
df_tactile = pd.DataFrame(mat['tactile_data'])
display(df_tactile.head(10))
print(mat['tactile_data'][0][:1000])

<class 'numpy.ndarray'>
(339989, 1024)


0     1     2     3     4     5     6     7     8     9     ...  1014  \
0  1647  1537  1569  1533  1511  1503  1511  1514  1566  1521  ...  1501   
1  1649  1537  1566  1533  1508  1506  1511  1515  1559  1519  ...  1497   
2  1643  1535  1569  1534  1510  1503  1507  1511  1559  1515  ...  1497   
3  1638  1532  1567  1534  1512  1500  1508  1515  1563  1516  ...  1497   
4  1639  1534  1564  1533  1509  1498  1506  1514  1559  1515  ...  1497   
5  1640  1535  1569  1534  1514  1502  1509  1512  1564  1514  ...  1497   
6  1641  1536  1573  1541  1514  1506  1509  1511  1568  1512  ...  1494   
7  1642  1533  1575  1540  1507  1501  1509  1510  1569  1510  ...  1497   
8  1641  1535  1570  1537  1510  1503  1509  1515  1563  1519  ...  1497   
9  1640  1536  1579  1540  1513  1503  1511  1514  1564  1513  ...  1497   

   1015  1016  1017  1018  1019  1020  1021  1022  1023  
0  1501  1500  1510  1506  1516  1505  1497  1500  1497  
1  1498  1498  1513  1512  1510  1499  1497  1496  1495  
2  1498  1498  1509  1512  1511  1498  1498  1497  1499  
3  1497  1497  1507  1515  1512  1501  1498  1497  1498  
4  1498  1494  1510  1511  1516  1500  1496  1497  1498  
5  1498  1498  1512  1510  1514  1499  1498  1499  1502  
6  1497  1497  1506  1511  1510  1503  1500  1500  1497  
7  1494  1497  1508  1508  1510  1501  1494  1497  1496  
8  1498  1497  1510  1515  1512  1502  1495  1497  1495  
9  1496  1498  1503  1510  1510  1498  1494  1496  1501  

[10 rows x 1024 columns]

[1647 1537 1569 1533 1511 1503 1511 1514 1566 1521 1508 1525 1511 1501
 1517 1505 1512 1512 1521 1526 1512 1533 1507 1512 1519 1523 1531 1539
 1515 1515 1525 1527 1647 1532 1574 1534 1511 1506 1506 1507 1563 1515
 1511 1527 1508 1499 1517 1509 1516 1521 1538 1536 1523 1545 1509 1514
 1522 1533 1538 1546 1524 1521 1532 1539 1628 1525 1554 1525 1507 1503
 1507 1515 1573 1519 1513 1519 1503 1501 1514 1515 1518 1524 1544 1544
 1545 1557 1510 1515 1519 1530 1537 1546 1527 1523 1537 1546 1499 1494
 1494 1497 1493 1496 1498 1499 1503 1498 1503 1509 1496 1502 1520 1514
 1524 1521 1547 1537 1529 1544 1510 1510 1515 1533 1541 1540 1527 1524
 1533 1548 1496 1497 1501 1495 1495 1498 1493 1498 1508 1498 1508 1510
 1502 1498 1533 1520 1532 1527 1566 1541 1533 1556 1513 1517 1519 1534
 1535 1541 1522 1520 1527 1547 1508 1498 1494 1496 1497 1496 1494 1496
 1502 1491 1507 1507 1502 1501 1540 1522 1530 1521 1563 1533 1529 1548
 1509 1511 1515 1529 1535 1535 1520 1516 1521 1543 1506 1512 1507 1499
 1510 

In [5]:

# IMU_data:
print(type(mat['IMU_data']))
print(mat['IMU_data'].shape)
df_imu = pd.DataFrame(mat['IMU_data'])
display(df_imu.head(6))

<class 'numpy.ndarray'>
(339989, 6)


0    1     2    3    4    5
0 -810 -220  8350  -17  752 -407
1 -790 -374  8450  176  696 -368
2 -740 -136  8478  454  526 -268
3 -656 -176  8364  343  677 -176
4 -682  -88  8382  394  800 -258
5 -770  -94  8316  416  779  -96

In [6]:
# object_id:
print(type(mat['object_id']))
print(mat['object_id'].shape)
print(mat['object_id'][0][:4000])

<class 'numpy.ndarray'>
(1, 339989)
[0 0 0 ... 0 0 0]


In [7]:
# valid_flag:
print(type(mat['valid_flag']))
print(mat['valid_flag'].shape)
print(mat['valid_flag'])

<class 'numpy.ndarray'>
(1, 339989)
[[1 1 1 ... 0 0 0]]


In [8]:
# sessions:
print(type(mat['session_id']))
print(mat['session_id'].shape)
print(mat['session_id'][0])



<class 'numpy.ndarray'>
(1, 339989)
[0 0 0 ... 4 4 4]


In [7]:
# Objects:
print(type(mat['objects']))
print(mat['objects'])
df_objects = pd.DataFrame(mat['objects'])
display(df_objects.head(17))


<class 'numpy.ndarray'>
['ball          ' 'battery       ' 'bracket       ' 'coin          '
 'empty_can     ' 'empty_hand    ' 'full_can      ' 'gel           '
 'lotion        ' 'mug           ' 'pen           ' 'safety_glasses'
 'scissors      ' 'screw_driver  ' 'spray_can     ' 'stapler       '
 'tape          ']


0
0   ball          
1   battery       
2   bracket       
3   coin          
4   empty_can     
5   empty_hand    
6   full_can      
7   gel           
8   lotion        
9   mug           
10  pen           
11  safety_glasses
12  scissors      
13  screw_driver  
14  spray_can     
15  stapler       
16  tape

In [11]:
# threshold:
print(type(mat['threshold']))
print(mat['threshold'].shape)
print(mat['threshold'][0][:1000])

<class 'numpy.ndarray'>
(1, 1024)
[1714 1632 1725 1629 1635 1655 1601 1570 1599 1623 1635 1589 1631 1602
 1801 1583 1608 1641 1830 1646 1595 1642 1594 1595 1579 1600 1686 1632
 1581 1595 1570 1582 1703 1622 1642 1608 1623 1583 1614 1557 1587 1603
 1595 1601 1633 1608 1743 1571 1624 1612 1863 1670 1625 1622 1608 1581
 1585 1610 1634 1622 1591 1581 1603 1587 1691 1629 1622 1586 1606 1634
 1591 1563 1639 1609 1604 1558 1617 1591 1684 1571 1611 1595 1790 1628
 1604 1614 1664 1565 1580 1594 1607 1597 1601 1589 1589 1573 1608 1607
 1607 1608 1607 1608 1609 1609 1611 1609 1618 1625 1631 1626 1717 1573
 1597 1587 1795 1651 1636 1649 1695 1581 1603 1610 1628 1595 1578 1591
 1591 1569 1609 1606 1607 1607 1607 1607 1607 1609 1613 1609 1617 1623
 1622 1623 1661 1615 1608 1596 1812 1644 1657 1659 1676 1601 1661 1637
 1701 1601 1583 1570 1579 1571 1622 1609 1609 1608 1607 1611 1609 1613
 1615 1619 1618 1629 1628 1633 1634 1665 1617 1595 1714 1621 1621 1683
 1611 1602 1608 1581 1642 1578 1568 1557 15